category_index:
  path: /category
  controller: App\Controller\CategoryController::index

category_add:
  path: /category/add
  controller: App\Controller\CategoryController::add

category_update:
  path: /category/edit/{id}
  controller: App\Controller\CategoryController::update